### ISSUE TITLE
"utils" missing from find_wally.py

### ISSUE THREAD

**Issue by SpireFlux** [tadejmagajna/HereIsWally#1]
The utils module (likely from the TF Object Detection repo) is missing from this repo.  

```
 HereIsWally git:(master) python3 find_wally.py 
Traceback (most recent call last):
  File "find_wally.py", line 8, in <module>
    from utils import label_map_util
ModuleNotFoundError: No module named 'utils'

```

**Comment by tadejmagajna** [comment]
Issue was related to having to run export ``export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim`` from `tensorflow/models/research/object_detection` and not `tensorflow/models/research/` like the tensorflow Object Detection API instruction say which could be regarded as a genuine bug.

I've implemented a solution that avoids having to install Object Detection API by including the required libraries in the repo.

You should be able to run it straight away now by pulling in the latest changes. Let me know if  that resolves the issue for you @SpireFlux

**Comment by SpireFlux** [comment]
I pulled the updates and the issue has been resolved.  Thank you!
