### ISSUE TITLE
Text Labels are potentially missing

### ISSUE THREAD

**Issue by SpireFlux** [tadejmagajna/HereIsWally#2]
In the first section "Preparing the dataset", you mention the labels corresponding to the images that would be packed into a single binary TF file.

I speculate this labels file is a collection of annotations in PASCAL VOC format, output from a program like labelImg.

This file seems to be missing from the repo.

Looking in `final.config`, is's possible that one of the two following files is our missing labels file.

    label_map_path: "/Users/tadej/waldo/labels.pbtxt"
    label_map_path: "/Users/tadej/waldo/labels.txt"

Please advise.

**Comment by tadejmagajna** [comment]
Hey,

labels I talk about in "Preparing the dataset" and `labels.txt` from section "Preparing the Model" are two different things

In "Preparing the dataset" the labels (I now updated the article to say `.csv` file to make it more clear) is a file that contains locations of all hand labelled Wally boxes in images - [ this file ](https://github.com/tadejmagajna/HereIsWally/blob/master/annotations/annotations.csv). You basically use this file and the images to create the binary `.tfrecord` files which are end result of this step. But the process on how to do that is not entirely explained in my article. I add a link on how to do it but point out that you can just use the `.tfrecord` files from my repo to make things simpler.

Then, in another section "Preparing the Model" I talk about a `labels.txt` file. This file doesn't have anything to do with annotations. It just tells Tensorflow Object Detection API that the class with id 1 is 'waldo' and it should display that label in the image when drawing the box around him.

Finally, the `final.config` in my repo (I now renamed it to `example.config` to make it clearer) is a pipeline file that tells Tensorflow how to train the model and where the `labels.txt` and test and train tfrecords are. I added some placeholders (like `PATH_TO_LABELS_FILE`) so make sure to replace these with correct paths. You can also use the [official pipeline config file](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_inception_v2_coco.config) like I mentioned in the article.

Thank you for raising the issue. I made some updates to make sure it's clearer for everyone else as well.
Hope that answers your question, @SpireFlux

**Comment by SpireFlux** [comment]
Ah, thank you.  The annotations `annotations.csv` file was the one that I was looking for.

Thank you!
